version: 2

sources:
    - name: tiller
      schema: tiller
      tables:
        - name: order
          identifier: tiller_order_data
        - name: product_line
          identifier: tiller_order_line
        - name: payment
          identifier: tiller_payment_data
        - name: store
          identifier: tiller_store_data
