version: 2
sources:
  - name: tiller
    description: datas on multiple restaurants using tiller
    loader: bigquery
    tables:
      - name: order_data
        description: Table of restaurant tables
        columns:
          - name: id_order
            description: Primary Key of the table
            tests:
              - unique
              - not_null
          - name : id_store
            description: Unique identification of the restaurant
          - name : id_table
            description: Unique identification of a table
          - name : Id_waiter
            description: Unique identification of a restaurant staff
          - name : Id_device
            description: Device id where order has been placed
          - name : Date_opened
            description: Device id where order has been placed
          - name : date_closed
            description: Table close date
          - name : Dim_status
            description: Status of the order
          - name : Dim_source
            description: Name of device where order has been placed
          - name : M_nb_customer
            description: Number of customers associated to order
          - name : M_cached_payed
            description: Price payed
          - name : M_cached_price
            description: Price to pay                
      - name: order_line
        description: Table of each product in each order
        columns:
          - name: id_order_line
            description: Primary Key of the table
            tests:
              - unique
              - not_null
          - name: Id_order
            description: Unique identification of an order
          - name: Date_opended
            description: Date item is ordered
          - name: Date_created
            description: Date item is saved
          - name: m_quantity
            description: Quantity
          - name: m_unit_price
            description: Price of an unit with vat
          - name: m_unit_price_exc_vat
            description: Price of an unit without vat 
          - name: m_total_price_inc_vat
            description: Total price of( unit * quantity) with vat
          - name: m_total_price_exc_vat
            description: Total price of( unit * quantity) without vat
          - name: m_tax_percent
            description: Vat percentage applied
          - name: m_discount_amount
            description: Discount
          - name: dim_type
            description:  Types (products, option, meal, discounts…)
          - name: dim_category
            description:  Category (beverages,Thé/cafe,Café Sachet,Suppléments …)
          - name: dim_name
            description: Item’s name (risotto, Tonic, Cidres, Mangue…)
          - name: dim_status
            description: Item status
          - name: dim_feature_type
            description: Item type
          - name: dim_unit_measure
            description: unit of measure of a product (UNIT, KILOGRAM,GRAM )
          - name: dim_unit_measure_display
            description: unit of measure of a product displayed (UNIT, KILOGRAM,GRAM )
          - name: dim_category_translated
            description: dim_category translated in english
          - name: dim_name_translated
            description: dim_name translated in english                                          
      - name: payment_data
        description: Table of payments details
        columns:
          - name: id_pay
            description: id of payment
            tests:
              - unique
              - not_null
          - name: id_order
            description: id_order corresponding to the payment. One id order can have several payment id (by type of payment mostly for example)
          - name: dim_status
            description: only "accepted" status, column to be dropped
          - name: dim_type
            description: Payment type (bank card, cash, ...)
          - name: m_amount
            description: Payment amount
          - name: m_cashback
            description: only 0, column to be dropped 
          - name: m_credit
            description: only 0, column to be dropped 
          - name: date_created
            description: date of the payment
      - name: store_data
        description: Table of different restaurants
        columns:
          - name: id_store
            description: Primary Key of the table, identifiant unique du restaurant 
            tests:
              - unique
              - not_null
          - name : date_created
            description : Subscription date of the restaurant to Sum up, not the time the restaurant opened 
          - name : dim_zipcode
            description : zipcode du restaurant
          - name : dim_country 
            description : conutry code of the restaurant 
          - name : Dim_currency 
            description : local currency of the restaurant 
      - name : type_service
        description: index des types de services 
        columns: 
          - name : hour
            description : heure du repas 
          - name : service
            description : type de service  
models:
  - name: int_sales_channel_performance
    tests:
      - unique:
          column_name: "(date_date || '-' || id_store || '-' || dim_type)"
      - not_null:
          column_name:
            - date_date
            - id_store
            - dim_type
    columns:
      - name: date_date
        description: date associated with store and payment method
      - name: id_store
        description: restaurant id number
      - name: dim_type
        description: payment method
      - name: turnover
        description: turnover associated to the payment method and date
  - name: int_product_performance
    description: Table of each product line in each order with the selected characteristics, joined with order_data to get id_store
    tests :
    - not_null:
          column_name:
            - id_store
            - id_order
            - date_opened
    columns:                 
      - name : id_store
        description : identifiant unique du restaurant
      - name: id_order
        description: Unique identification of an order 
      - name: Date_opened
        description: Table open date from order_data
      - name: id_order_line
        description: Primary Key of the table
        tests:
          - unique
          - not_null
      - name: dim_type
        description:  Types (products, option, meal, discounts…)
      - name: dim_category
        description:  Category (beverages,Thé/cafe,Café Sachet,Suppléments …)
      - name: dim_name
        description: Item’s name (risotto, Tonic, Cidres, Mangue…)
      - name: dim_feature_type
        description: Item type
      - name: m_quantity
        description: Quantity
      - name: m_unit_price
        description: Price of an unit with vat
      - name: m_total_price_inc_vat
        description: Total price of( unit * quantity) with vat
  - name: int_global_performance
    description: Table of each id order with corresponding waiter and table infos inc. nb customers, turnover and time spent on table
    tests:
      - not_null:
          column_name:
            - id_store
            - date_opened
            - date_closed
            - m_cached_payed
    columns:
      - name: id_store
        description: id of the store
      - name: id_order
        description: Primary Key of the table
        tests:
          - unique
          - not_null
      - name: id_table
        description: id of the table (one id table by order id)
      - name: id_waiter
        description: id of the waiter in charge of the table (one waiter id by order id)
      - name: date_opened
        description: date/hour when the table is opened
      - name: date_closed
        description: date/hour when the table is closed
      - name: minutes_on_a_table
        description: time spent on the table(s) in minutes
      - name: m_nb_customer 
        description: number of people at the table
      - name: m_cached_payed
        description: order price paid
